dist: xenial
language: node_js
node_js:
  - 12

env:
    - CHROME_BIN=google-chrome-stable

addons:
  chrome: stable
service:
  - xvfb
before_script:
  - npm install
  - cp src/app/firebaseConfig.ts.dummy src/app/firebaseConfig.ts

jobs:
  include:
    - stage: Linter
      script: npx eslint --ext .ts ./
    - stage: Test
      script: npm test
    - stage: Build and deploy
      script: npx ng build
