os: linux
dist: xenial
language: node_js
node_js:
  - 12

env:
    - CHROME_BIN=google-chrome-stable

addons:
  chrome: stable
services:
  - xvfb

before_script:
  - npm install
  - cp src/app/firebaseConfig.ts.dummy src/app/firebaseConfig.ts

jobs:
  include:
    - stage: Test
      script: npx ng test --watch false --browsers ChromeHeadless
    - stage: Build and deploy
      if: repo = MartinREMY42/multi-game-project AND branch = master
      script:
        - openssl aes-256-cbc -K $encrypted_bdd73078a253_key -iv $encrypted_bdd73078a253_iv -in .travis/firebaseConfig.ts.enc -out src/app/firebaseConfig.ts -d
        - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/id_rsa.enc -out id_rsa -d
        - npx ng build
        - sh .travis/deploy.sh
    - stage: Linter
      script: npx eslint --ext .ts ./

