dist: xenial
language: node_js
node_js:
  - 12

env:
    - CHROME_BIN=google-chrome-stable

addons:
  chrome: stable
service:
  - xvfb
before_script:
  - npm install
  - cp src/app/firebaseConfig.ts.dummy src/app/firebaseConfig.ts
