os: linux
dist: xenial
language: node_js
node_js:
  - 12

env:
    - CHROME_BIN=google-chrome-stable

addons:
  chrome: stable
services:
  - xvfb

before_script:
  - npm install
  - cp src/app/firebaseConfig.ts.dummy src/app/firebaseConfig.ts

jobs:
  include:
    - stage: Test
      script: npx ng test --watch false --browsers ChromeHeadless
    - stage: Build and deploy
      if: repo = MartinREMY42/multi-game-project AND branch = master
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh ./.travis/deploy.sh; fi'
    - stage: Linter
      script: npx eslint --ext .ts ./

