name: CI/CD On Action

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/setup@5911f5521254c44a09888c5009998955cd1ab875
      - name: Build
        run: npm run build

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/setup@5911f5521254c44a09888c5009998955cd1ab875
      - name: Run test suite
        run: npm run test:ci
      - name: Install python dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: lxml selenium pandas
      - name: Check coverage
        run: python ./scripts/coverage.py check

  linter:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/setup@5911f5521254c44a09888c5009998955cd1ab875
      - name: Run linter with dev config
        run: npm run lint
      - name: Run linter with stricter CI config
        run: npm run lint:ci

  images:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check the presence of all game images
        run: ./scripts/check-images.sh

  translations:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/setup@5911f5521254c44a09888c5009998955cd1ab875
      - name: Install python dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: pandas
      - name: Update translations
        run: ./scripts/update-translations.sh
      - name: Check completeness of translations
        run: ./scripts/check-translations.sh

