name: CI/CD On Develop Action

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        base-href: [/board-dev/]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build--${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-v2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Setup Firebase
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$ENC_SECRET" --output src/app/firebaseConfig.ts .github/firebaseConfig.ts.gpg
        env:
          ENC_SECRET: ${{ secrets.ENC_SECRET }}
      - name: Run linter
        run: npm run lint
        continue-on-error: true
      - name: Launch tests
        run: npm run test:ci
      - name: Build
        run: npm run build -- --base-href=${{ matrix.base-href }}
      - name: Deploy develop
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/pantheonsgame/
          remote_path: /var/www/html/${{ matrix.base-href }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
